import { Text } from "./Text";
import { Heading } from "./Heading";
import { Button } from "./Button";
import { Img } from "./Img";
import { Input } from "./Input";
import { Slider } from "./Slider";
import { TextArea } from "./TextArea";
import { CheckBox } from "./CheckBox";
import { SelectBox } from "./SelectBox";
export { Text, Heading, Button, Img, Input, Slider, TextArea, CheckBox, SelectBox };
